### ISSUE TITLE
Automatic Adjustment of Pickle File

### ISSUE THREAD

**Issue by tydickinson29** [Brigoon/DumbBot#22]
Implement a way to automatically adjust pickle file if we ever make changes to HeraldUser constructor. This will avoid users having to re-run /herald commands after software changes.

**Comment by Brigoon** [comment]
I think this function would need to work by taking a pickle file as input and loading in the old HeraldUser dictionary and then go through every entry and copy the old data to new HeraldUser classes and then into a new dictionary, dumping that into the pickle file

**Comment by tydickinson29** [comment]
I like your thoughts so far. In case of renaming class attributes or adding new ones, the function would need to compare the old attributes to the new ones and look for changes. Any attributes that are not changed can be copied directly and attributes that may change name can also be copied just with the new name. New attributes should be easy to add since they will be the default value for all users initially.
